package com.ksu.grad.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "Country", catalog = "EMAS", uniqueConstraints = @UniqueConstraint(columnNames = "Code"))
public class Country implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private boolean isActive;
	private boolean zipActive;
	private Set<State> states = new HashSet<State>(0);

	public Country() {
	}

	public Country(String name, String code, boolean isActive, boolean zipActive) {
		this.name = name;
		this.code = code;
		this.isActive = isActive;
		this.zipActive = zipActive;
	}

	public Country(String name, String code, boolean isActive, boolean zipActive, Set<State> states) {
		this.name = name;
		this.code = code;
		this.isActive = isActive;
		this.zipActive = zipActive;
		this.states = states;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Code", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "ZipActive", nullable = false)
	public boolean isZipActive() {
		return this.zipActive;
	}

	public void setZipActive(boolean zipActive) {
		this.zipActive = zipActive;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "country")
	public Set<State> getStates() {
		return this.states;
	}

	public void setStates(Set<State> states) {
		this.states = states;
	}

}
