package com.ksu.grad.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "Department", catalog = "EMAS", uniqueConstraints = @UniqueConstraint(columnNames = "Label"))
public class Department implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private String label;
	private String description;
	private int weightId;

	public Department() {
	}

	public Department(Employee employee, String label, int weightId) {
		this.employee = employee;
		this.label = label;
		this.weightId = weightId;
	}

	public Department(Employee employee, String label, String description, int weightId) {
		this.employee = employee;
		this.label = label;
		this.description = description;
		this.weightId = weightId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ManagerId", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "Label", unique = true, nullable = false, length = 45)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "WeightId", nullable = false)
	public int getWeightId() {
		return this.weightId;
	}

	public void setWeightId(int weightId) {
		this.weightId = weightId;
	}

}
