package com.ksu.grad.entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeHistory generated by hbm2java
 */
@Entity
@Table(name = "EmployeeHistory", catalog = "EMAS")
public class EmployeeHistory implements java.io.Serializable {

	private EmployeeHistoryId id;
	private AttributeStatus attributeStatus;
	private Employee employeeByEmployeeId;
	private Employee employeeByModifiedBy;
	private String information;

	public EmployeeHistory() {
	}

	public EmployeeHistory(EmployeeHistoryId id, AttributeStatus attributeStatus, Employee employeeByEmployeeId,
			Employee employeeByModifiedBy) {
		this.id = id;
		this.attributeStatus = attributeStatus;
		this.employeeByEmployeeId = employeeByEmployeeId;
		this.employeeByModifiedBy = employeeByModifiedBy;
	}

	public EmployeeHistory(EmployeeHistoryId id, AttributeStatus attributeStatus, Employee employeeByEmployeeId,
			Employee employeeByModifiedBy, String information) {
		this.id = id;
		this.attributeStatus = attributeStatus;
		this.employeeByEmployeeId = employeeByEmployeeId;
		this.employeeByModifiedBy = employeeByModifiedBy;
		this.information = information;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "validFrom", column = @Column(name = "ValidFrom", nullable = false, length = 19)),
			@AttributeOverride(name = "employeeId", column = @Column(name = "EmployeeId", nullable = false)) })
	public EmployeeHistoryId getId() {
		return this.id;
	}

	public void setId(EmployeeHistoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "AttributeStatusId", nullable = false)
	public AttributeStatus getAttributeStatus() {
		return this.attributeStatus;
	}

	public void setAttributeStatus(AttributeStatus attributeStatus) {
		this.attributeStatus = attributeStatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EmployeeId", nullable = false, insertable = false, updatable = false)
	public Employee getEmployeeByEmployeeId() {
		return this.employeeByEmployeeId;
	}

	public void setEmployeeByEmployeeId(Employee employeeByEmployeeId) {
		this.employeeByEmployeeId = employeeByEmployeeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ModifiedBy", nullable = false)
	public Employee getEmployeeByModifiedBy() {
		return this.employeeByModifiedBy;
	}

	public void setEmployeeByModifiedBy(Employee employeeByModifiedBy) {
		this.employeeByModifiedBy = employeeByModifiedBy;
	}

	@Column(name = "Information", length = 65535)
	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

}
