package com.ksu.grad.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeHistoryId generated by hbm2java
 */
@Embeddable
public class EmployeeHistoryId implements java.io.Serializable {

	private Date validFrom;
	private int employeeId;

	public EmployeeHistoryId() {
	}

	public EmployeeHistoryId(Date validFrom, int employeeId) {
		this.validFrom = validFrom;
		this.employeeId = employeeId;
	}

	@Column(name = "ValidFrom", nullable = false, length = 19)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Column(name = "EmployeeId", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeHistoryId))
			return false;
		EmployeeHistoryId castOther = (EmployeeHistoryId) other;

		return ((this.getValidFrom() == castOther.getValidFrom()) || (this.getValidFrom() != null
				&& castOther.getValidFrom() != null && this.getValidFrom().equals(castOther.getValidFrom())))
				&& (this.getEmployeeId() == castOther.getEmployeeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getValidFrom() == null ? 0 : this.getValidFrom().hashCode());
		result = 37 * result + this.getEmployeeId();
		return result;
	}

}
