package com.ksu.grad.entity;
// Generated Nov 16, 2017 10:28:30 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "Login", catalog = "EMAS", uniqueConstraints = @UniqueConstraint(columnNames = "UserName"))
public class Login implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private String resetToken;
	private Date validUntil;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Login() {
	}

	public Login(String userName, String password, String resetToken) {
		this.userName = userName;
		this.password = password;
		this.resetToken = resetToken;
	}

	public Login(String userName, String password, String resetToken, Date validUntil, Set<Employee> employees) {
		this.userName = userName;
		this.password = password;
		this.resetToken = resetToken;
		this.validUntil = validUntil;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ResetToken", nullable = false, length = 64)
	public String getResetToken() {
		return this.resetToken;
	}

	public void setResetToken(String resetToken) {
		this.resetToken = resetToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ValidUntil", length = 19)
	public Date getValidUntil() {
		return this.validUntil;
	}

	public void setValidUntil(Date validUntil) {
		this.validUntil = validUntil;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "login")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
