package com.ksu.grad.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "Status", catalog = "EMAS", uniqueConstraints = @UniqueConstraint(columnNames = "Label"))
public class Status implements java.io.Serializable {

	private Integer id;
	private String label;
	private String description;
	private Set<AttributeStatus> attributeStatuses = new HashSet<AttributeStatus>(0);

	public Status() {
	}

	public Status(String label) {
		this.label = label;
	}

	public Status(String label, String description, Set<AttributeStatus> attributeStatuses) {
		this.label = label;
		this.description = description;
		this.attributeStatuses = attributeStatuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Label", unique = true, nullable = false, length = 45)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status")
	public Set<AttributeStatus> getAttributeStatuses() {
		return this.attributeStatuses;
	}

	public void setAttributeStatuses(Set<AttributeStatus> attributeStatuses) {
		this.attributeStatuses = attributeStatuses;
	}

}
